#!/usr/bin/python3 -W ignore::DeprecationWarning
# -*- coding:utf8 -*-
import warnings
warnings.filterwarnings('ignore')
import logging
logging.disable(level=logging.CRITICAL)
import sys
from Asking.t5_boolean import YesNoQuestionGenerator
from Asking.advance_qg import QuestionGenerator
from Asking.advance_qg import print_qa

if __name__ == '__main__':
    input_file = sys.argv[1]
    N = int(sys.argv[2])
    N_yesNo = int(N / 2)
    N_A = N - N_yesNo

    with open(input_file, encoding="UTF-8") as a:
        article = a.read()

    if N_A>0:
        qg = QuestionGenerator()
        qa_list = qg.generate(
            article,
            use_evaluator=True,
            num_questions=N_A,
        )
        # print qa
        print_qa(qa_list, show_answers=False)

    if N_yesNo > 0:
        qg_yesNo = YesNoQuestionGenerator(article, N_yesNo)
        yesNo_questions = qg_yesNo.generate()
        # print yes or no dataset
        for question in yesNo_questions:
            print(f'{question}')

    with open('output.txt', 'w') as f:
        if N_yesNo > 0:
            for question in yesNo_questions:
                print(f'{question}', file=f)
        if N_A > 0:
            for i in range(len(qa_list)):
                print(f"{qa_list[i]['question']}", file=f)
            #print_qa(qa_list, show_answers=False)

    sys.exit(0)
